import Header from "./components/header";
import Footer from "./components/footer";
import Content from "./components/content";
import CategoryFilter from "./components/categoryFilter";
import Banner from "./components/banner";
import "./App.css";

function App() {
  return (
    <main className="min-h-screen">
      {/* <Head>
        <title>airbnb clone</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/assets/logo.svg" />
      </Head> */}

      <Banner />
      <Header />
      <CategoryFilter />
      <Content />
      <Footer />
    </main>
  );
}

export default App;
